version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    environment:
    - RAILS_MASTER_KEY=f24a5a31125d396de3502cff162be9b1
    - DATABASE_URL=postgres://postgres:postgres@db:5432/blog_api_development
    - RAILS_ENV=development

    build: .
    command: ./bin/thrust ./bin/rails server -b 0.0.0.0
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  sidekiq:
    environment:
      - RAILS_MASTER_KEY=f24a5a31125d396de3502cff162be9b1
      - DATABASE_URL=postgres://postgres:postgres@db:5432/blog_api_development
      - RAILS_ENV=development
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/rails
    depends_on:
      - db
      - redis

volumes:
  pgdata:
